---

- name: install ngrok
  sudo: true
  copy: 
    src=ngrok
    dest=/usr/local/bin
    owner={{ application_user }}
    group={{ application_user }}
    mode=0777

- name: add an ngrok upstart job
  sudo: true
  template:
    src=ngrok.upstart.j2
    dest=/etc/init/ngrok.conf
    owner=root
    group=root
    mode=0644
  notify: restart ngrok
