---

- name: Create the celerybeat schedule directory
  sudo: True
  file: 
    path=/etc/celery
    state=directory
    owner={{ application_user }}
    group={{ application_user }}
    mode=755

- name: Install celerybeat init
  sudo: True
  copy:
    src=celerybeat.init
    dest=/etc/init.d/celerybeat
    owner=root
    group=root
    mode=755
  notify:
    - restart celerybeat

- name: Install celerybeat config
  sudo: True
  template:
    src=celerybeat.j2
    dest=/etc/default/celerybeat
    owner=root
    group=root
    mode=644
  notify:
    - restart celerybeat

- name: Enable celerybeat
  sudo: True
  service:
    name=celerybeat
    state={{ celerybeat_state }}
    enabled=True
