---

- hosts: localhost
  roles:
    - application_package
    - uwsgi
    - celeryd
    - beatcop  # controls celerybeat cluster
    - monit
  tasks:
    - include: roles/confd/tasks/configs.yml confd_profile=website-server
  vars:
    application_server_name: test.sitterfied.com
    application_user: ubuntu
    celeryd_state: stopped
    env: deployed
    monit_state: "stopped"
    uwsgi_proceses: 6
    uwsgi_user: ubuntu
