---

supervisor_config_dir: "/etc/supervisor/conf.d/"
supervisorctl_command: "supervisorctl"
redirect_stderr: "true"
supervisor_port: 9001
autorestart: "true"
startsecs: 2
autostart: "true"
env_vars: {}
