---

- name: install the fakeroot package
  sudo: true
  apt: name=fakeroot state=present

- name: set the sticky bit on the top-level build directory
  sudo: true
  file: path={{ packaging_build_dir }} state=directory
    owner=root group=root mode=1777

- name: copy the build files into the build directory
  sudo: true
  sudo_user: "{{ packaging_user }}"
  copy: src=build-tree/ dest={{ packaging_build_dir }}

- name: fix permissions on executable scripts
  sudo: true
  sudo_user: "{{ packaging_user }}"
  command: "/usr/bin/find {{ packaging_build_dir }} -type f ( -name 'postinst' -o -name 'prerm' ) -exec chmod 0755 {} +"
  changed_when: false

- name: copy the package generation script
  sudo: true
  template: src=generate-website-server-package.sh.j2
    dest=/usr/local/bin/generate-website-server-package
    owner=root group=root mode=0755
