---

- name: write monitors
  sudo: true
  copy: 
    src: "{{ item }}"
    dest: "/etc/monit/conf.d/{{ item | basename }}"
    owner: root
    group: root
  with_fileglob:
    - configs/conf.d/*
  notify: restart monit
