---
- name: monitors - Write monitors
  sudo: true
  template:
    src: monitor.j2
    dest: "/etc/monit/conf.d/{{ item.name }}"
    owner: root
    group: root
  with_items: monit_services
  notify: restart monit
