---

- name: install supervisor
  apt: pkg=supervisor state=present update_cache=true
  sudo: true

- name: start supervisor and enable it on boot
  service: name=supervisor state=started enabled=true
  sudo: true

- name: installing task {{ name }}
  template: src=task.conf.j2 dest={{ supervisor_config_dir }}/{{ name }}.conf
  register: supervisor_task_conf
  sudo: true

- name: starting {{ name }}
  supervisorctl: name={{ name }} state=present
  register: supervisor_task_started
  sudo: true

- name: reloading conf for {{ name }}
  when: supervisor_task_conf|changed and not supervisor_task_started|changed
  supervisorctl: name={{ name }} state=restarted
  sudo: true
