---

- name: download the confd binary
  sudo: true
  get_url: url=https://github.com/kelseyhightower/confd/releases/download/v{{ confd_version }}/confd-{{ confd_version }}-linux-amd64
    dest=/usr/local/bin/confd
    owner=root group=root mode=0755

- name: create the confd configuration directories
  sudo: true
  file: path={{ item }} state=directory
    owner=root group=root mode=0755
  with_items:
    - /etc/confd/conf.d
    - /etc/confd/templates

- name: add the confd configuration file
  sudo: true
  copy: src=confd.toml dest=/etc/confd/confd.toml
    owner=root group=root mode=0644
  notify:
    - run confd

- name: add a confd upstart job
  sudo: true
  copy: src=confd.upstart dest=/etc/init/confd.conf
    owner=root group=root mode=0644

- name: start the confd daemon and enable it on boot
  sudo: true
  service: name=confd state=stopped enabled=yes
