#!/bin/bash

echo "syncdb"
/home/dotcloud/current/manage.py syncdb --noinput

echo "migrate"
/home/dotcloud/current/manage.py migrate --noinput

echo "collectstatic"
/home/dotcloud/current/manage.py collectstatic --noinput

echo "notify slack of deployment"
REVISION=`cd .. && ls | grep rsync`
MESSAGE="Build $REVISION was deployed to $DOTCLOUD_PROJECT.$DOTCLOUD_SERVICE_NAME.$DOTCLOUD_SERVICE_ID."
curl -X POST --data-urlencode "payload={\"channel\": \"#general\", \"username\": \"dotCloud\", \"text\": \"$MESSAGE\"}" https://sitterfied.slack.com/services/hooks/incoming-webhook?token=uGwyPaDHU0gvyEs267453khP
