---

- name: Install celeryd init
  sudo: True
  copy:
    src=celeryd.init
    dest=/etc/init.d/celeryd
    owner=root
    group=root
    mode=755
  notify:
    - restart celeryd

- name: Install celeryd clean restart script
  sudo: True
  copy:
    src=celeryd-clean-restart.sh
    dest=/usr/local/bin/celeryd-clean-restart
    owner=root
    group=root
    mode=755

- name: Install celeryd config
  sudo: True
  template:
    src=celeryd.j2
    dest=/etc/default/celeryd
    owner=root
    group=root
    mode=644
  notify:
    - restart celeryd

- name: Enable celeryd
  sudo: True
  service:
    name=celeryd
    state={{ celeryd_state }}
    enabled=True
