---

- name: install celeryd init
  become: true
  copy:
    src=celeryd.init
    dest=/etc/init.d/celeryd
    owner=root
    group=root
    mode=755
  notify:
    - restart celeryd

- name: install celeryd clean restart script
  become: true
  copy:
    src=celeryd-clean-restart.sh
    dest=/usr/local/bin/celeryd-clean-restart
    owner=root
    group=root
    mode=755

- name: install celeryd config
  become: true
  template:
    src=celeryd.j2
    dest=/etc/default/celeryd
    owner=root
    group=root
    mode=644
  notify:
    - restart celeryd

- name: enable celeryd on boot
  become: true
  service:
    name=celeryd
    state={{ celeryd_state }}
    enabled=true
