#!/usr/bin/env python
import json
import os

import psycopg2
import psycopg2.extras
import requests


def get_connection():
    """Get a connection, if a connect cannot be made an exception will be raised here"""

    conn_string = "host='{0}' port='{1}' dbname='sitterfied' user='{2}' password='{3}'".format(
        env.get('DOTCLOUD_DATA_SQL_HOST'),
        env.get('DOTCLOUD_DATA_SQL_PORT'),
        env.get('DOTCLOUD_DATA_SQL_LOGIN'),
        env.get('DOTCLOUD_DATA_SQL_PASSWORD')
    )

    # print the connection string we will use to connect
    #print("Connecting to database\n	->%s" % (conn_string))

    # get a connection, if a connection cannot be made an exception will be raised here
    return psycopg2.connect(conn_string)


def get_friends(parent_id):
    friends = []

    query = """
SELECT
    f.id as friend_id,
    f.first_name || ' ' || f.last_name as friend_name,
    f.email as friend_email,
    f.avatar as friend_avatar
FROM public.app_parent as p
LEFT OUTER JOIN public.app_user up on up.id = p.user_ptr_id
LEFT OUTER JOIN public.app_user_friends uf on uf.from_user_id = up.id
LEFT OUTER JOIN public.app_user f on f.id = uf.to_user_id
WHERE up.id = {0}
GROUP BY up.id, f.id, f.first_name, f.last_name, f.email, f.avatar
ORDER BY up.id
    """.format(parent_id)

    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
    cursor.execute(query)
    records = cursor.fetchall()

    for record in records:
        if record['friend_id']:
            friend = {
                'id': record['friend_id'],
                'name': record['friend_name'],
                'email': record['friend_email'],
                'avatar': record['friend_avatar'],
            }
            friends.append(friend)

    return friends


def get_sitters(parent_id):
    sitters = []

    query = """
SELECT
    us.id as sitter_id,
    us.first_name || ' ' || us.last_name as sitter_name,
    us.email as sitter_email,
    us.avatar as sitter_avatar
FROM public.app_parent as p
LEFT OUTER JOIN public.app_user up on up.id = p.user_ptr_id
LEFT OUTER JOIN public.app_parent_sitter_teams t on up.id = t.parent_id
LEFT OUTER JOIN public.app_user us on us.id = t.sitter_id
WHERE up.id = {0}
GROUP BY us.id, up.id, us.first_name, us.last_name, us.email, us.avatar
ORDER BY up.id
    """.format(parent_id)

    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
    cursor.execute(query)
    records = cursor.fetchall()

    for record in records:
        if record['sitter_id']:
            sitter = {
                'id': record['sitter_id'],
                'name': record['sitter_name'],
                'email': record['sitter_email'],
                'avatar': record['sitter_avatar'],
            }
            sitters.append(sitter)

    return sitters


def get_parents():
    query = """
SELECT
    up.id as parent_id,
    up.first_name as first_name,
    up.last_name as last_name,
    up.email as email
FROM public.app_parent as p
LEFT OUTER JOIN public.app_user up on up.id = p.user_ptr_id
GROUP BY up.id, up.first_name, up.last_name, up.email
ORDER BY up.id"""

    cursor = conn.cursor(cursor_factory=psycopg2.extras.DictCursor)
    cursor.execute(query)
    return cursor.fetchall()


def main():
    records = get_parents()

    data = {'contacts': []}

    for record in records:
        parent_id = record['parent_id']

        parent = {}
        parent['name'] = record['first_name'].strip() + " " + record['last_name'].strip()
        parent['email'] = record['email'].strip()
        parent['data'] = {
            'id': parent_id,
            'first_name': record['first_name'].strip(),
            'last_name': record['last_name'].strip(),
        }

        friends = get_friends(parent_id)
        parent['data']['friends'] = friends
        parent['data']['num_friends'] = len(friends)

        sitters = get_sitters(parent_id)
        parent['data']['sitters'] = sitters
        parent['data']['sitter_team_size'] = len(sitters)

        data['contacts'].append(parent)

    # print('Request body\n	->%s' % (json.dumps(data)))

    api_token = env.get('KNOWTIFY_API_TOKEN')
    if api_token:
        try:
            r = requests.post(
                'http://www.knowtify.io/api/v1/contacts/upsert',
                data=json.dumps(data),
                headers={'Authorization': 'Token token="' + api_token + '"'}
            )
            print('API response\n      ->%s' % (r.content))
        except Exception as e:
            print('API error\n	->%s' % (e.message))
    else:
        print('An error occurred\n       ->The Knowtify API token is not set. Please set the KNOWTIFY_API_TOKEN environment variable.')


try:
    with open('/home/dotcloud/environment.json') as f:
        env = json.load(f)
except:
    # This is for testing purposes and will load variables from the
    # local environment if possible.
    env = {}
    env['DOTCLOUD_DATA_SQL_HOST'] = os.environ.get('DOTCLOUD_DATA_SQL_HOST')
    env['DOTCLOUD_DATA_SQL_PORT'] = os.environ.get('DOTCLOUD_DATA_SQL_PORT')
    env['DOTCLOUD_DATA_SQL_LOGIN'] = os.environ.get('DOTCLOUD_DATA_SQL_LOGIN')
    env['DOTCLOUD_DATA_SQL_PASSWORD'] = os.environ.get('DOTCLOUD_DATA_SQL_PASSWORD')
    env['KNOWTIFY_API_TOKEN'] = os.environ.get('KNOWTIFY_API_TOKEN')


conn = get_connection()


if __name__ == "__main__":
    main()
