# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding field 'Parent.default_payment_method_token'
        db.add_column(u'app_parent', 'default_payment_method_token',
                      self.gf('django.db.models.fields.CharField')(default='', max_length=20, blank=True),
                      keep_default=False)


    def backwards(self, orm):
        # Deleting field 'Parent.default_payment_method_token'
        db.delete_column(u'app_parent', 'default_payment_method_token')


    models = {
        u'app.address': {
            'Meta': {'object_name': 'Address'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['app.User']"})
        },
        u'app.booking': {
            'Meta': {'object_name': 'Booking'},
            'accepted_sitter': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['app.Sitter']", 'null': 'True', 'blank': 'True'}),
            'address1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'address2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'booking_status': ('django.db.models.fields.CharField', [], {'default': "'Active'", 'max_length': '10'}),
            'booking_type': ('django.db.models.fields.CharField', [], {'default': "'Job'", 'max_length': '20'}),
            'canceled': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            'declined_sitters': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "'declined_bookings'", 'blank': 'True', 'to': u"orm['app.Sitter']"}),
            'emergency_phone': ('django.db.models.fields.CharField', [], {'max_length': '12', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'notes': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'num_children': ('django.db.models.fields.IntegerField', [], {'default': '1'}),
            'overnight': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'parent': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'bookings'", 'to': u"orm['app.Parent']"}),
            'rate': ('django.db.models.fields.DecimalField', [], {'default': '0', 'max_digits': '5', 'decimal_places': '2', 'blank': 'True'}),
            'respond_by': ('django.db.models.fields.DateTimeField', [], {'null': 'True', 'blank': 'True'}),
            'sitters': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'bookings'", 'symmetrical': 'False', 'to': u"orm['app.Sitter']"}),
            'start_date_time': ('django.db.models.fields.DateTimeField', [], {}),
            'state': ('django.db.models.fields.CharField', [], {'default': "'AL'", 'max_length': '2', 'blank': 'True'}),
            'stop_date_time': ('django.db.models.fields.DateTimeField', [], {}),
            'zip': ('django.db.models.fields.CharField', [], {'max_length': '9', 'blank': 'True'})
        },
        u'app.certification': {
            'Meta': {'object_name': 'Certification'},
            'certification': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '128'}),
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'})
        },
        u'app.child': {
            'Meta': {'object_name': 'Child'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            'dob': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'null': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'name': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '50', 'blank': 'True'}),
            'parent': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'children'", 'to': u"orm['app.Parent']"}),
            'school': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '50', 'blank': 'True'}),
            'special_needs': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['app.SpecialNeed']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'app.contact': {
            'Meta': {'object_name': 'Contact'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'}),
            'phone': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['app.Phone']"})
        },
        u'app.group': {
            'Meta': {'object_name': 'Group'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '128'})
        },
        u'app.incomingsmsmessage': {
            'Meta': {'object_name': 'IncomingSMSMessage'},
            'body': ('django.db.models.fields.CharField', [], {'max_length': '161'}),
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            'date_created': ('django.db.models.fields.DateTimeField', [], {}),
            'date_sent': ('django.db.models.fields.DateTimeField', [], {}),
            'date_updated': ('django.db.models.fields.DateTimeField', [], {}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'sid': ('django.db.models.fields.CharField', [], {'max_length': '34'}),
            'status': ('django.db.models.fields.CharField', [], {'max_length': '12'}),
            'to': ('django.db.models.fields.CharField', [], {'max_length': '16'})
        },
        u'app.language': {
            'Meta': {'object_name': 'Language'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'language': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'})
        },
        u'app.otherservice': {
            'Meta': {'object_name': 'OtherService'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'service': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '128'})
        },
        u'app.parent': {
            'Meta': {'object_name': 'Parent', '_ormbases': [u'app.User']},
            'billing_address1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'billing_address2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '255', 'blank': 'True'}),
            'bookmarks': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "'bookmarks'", 'blank': 'True', 'to': u"orm['app.Sitter']"}),
            'default_payment_method_token': ('django.db.models.fields.CharField', [], {'max_length': '20', 'blank': 'True'}),
            'emergency_contact_one_name': ('django.db.models.fields.CharField', [], {'max_length': '128', 'blank': 'True'}),
            'emergency_contact_one_phone': ('django.db.models.fields.CharField', [], {'max_length': '10', 'blank': 'True'}),
            'emergency_contact_two_name': ('django.db.models.fields.CharField', [], {'max_length': '128', 'blank': 'True'}),
            'emergency_contact_two_phone': ('django.db.models.fields.CharField', [], {'max_length': '10', 'blank': 'True'}),
            'payment_method': ('django.db.models.fields.CharField', [], {'max_length': '15', 'blank': 'True'}),
            'sitter_teams': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "'sitter_teams'", 'blank': 'True', 'to': u"orm['app.Sitter']"}),
            u'user_ptr': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['app.User']", 'unique': 'True', 'primary_key': 'True'})
        },
        u'app.phone': {
            'Meta': {'object_name': 'Phone'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'number': ('django.db.models.fields.CharField', [], {'max_length': '25'}),
            'phone_type': ('django.db.models.fields.CharField', [], {'default': "'work'", 'max_length': '10'}),
            'primary': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'user': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['app.User']"})
        },
        u'app.reminder': {
            'Meta': {'object_name': 'Reminder'},
            'booking': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['app.Booking']"}),
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'task_id': ('django.db.models.fields.CharField', [], {'max_length': '256'})
        },
        u'app.schedule': {
            'Meta': {'object_name': 'Schedule'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            'fri_early_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'fri_early_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'fri_early_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'fri_late_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'fri_late_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'fri_late_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'fri_overnight': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'mon_early_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mon_early_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mon_early_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mon_late_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mon_late_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mon_late_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mon_overnight': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sat_early_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sat_early_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sat_early_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sat_late_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sat_late_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sat_late_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sat_overnight': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sitter': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['app.Sitter']", 'unique': 'True'}),
            'sun_early_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sun_early_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sun_early_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sun_late_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sun_late_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sun_late_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'sun_overnight': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'thu_early_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'thu_early_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'thu_early_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'thu_late_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'thu_late_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'thu_late_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'thu_overnight': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'tue_early_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'tue_early_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'tue_early_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'tue_late_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'tue_late_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'tue_late_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'tue_overnight': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'wed_early_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'wed_early_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'wed_early_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'wed_late_afternoon': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'wed_late_evening': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'wed_late_morning': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'wed_overnight': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'app.settings': {
            'Meta': {'object_name': 'Settings'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            'email_blog': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'email_booking_accepted_denied': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'email_booking_request': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'email_friend_joined': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'email_groups_added_network': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'email_new_review': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'email_news': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'email_upcoming_booking_remind': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'mobile_booking_accepted_denied': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mobile_booking_request': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mobile_friend_joined': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mobile_groups_added_network': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mobile_new_review': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'mobile_upcoming_booking_remind': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'user': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['app.User']", 'unique': 'True', 'null': 'True'})
        },
        u'app.sitter': {
            'Meta': {'object_name': 'Sitter', '_ormbases': [u'app.User']},
            'biography': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'cats_ok': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'certifications': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['app.Certification']", 'symmetrical': 'False', 'blank': 'True'}),
            'current_student': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'dob': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'dogs_ok': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'extra_exp': ('django.db.models.fields.TextField', [], {'default': "''", 'null': 'True', 'blank': 'True'}),
            'gender': ('django.db.models.fields.CharField', [], {'default': "'female'", 'max_length': '10'}),
            'has_drivers_licence': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'highest_education': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'id_verified': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'infant_exp': ('django.db.models.fields.SmallIntegerField', [], {'blank': 'True'}),
            'last_school': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'major': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'occupation': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'one_child_max_rate': ('django.db.models.fields.DecimalField', [], {'max_digits': '5', 'decimal_places': '2'}),
            'one_child_min_rate': ('django.db.models.fields.DecimalField', [], {'max_digits': '5', 'decimal_places': '2'}),
            'other_animals_ok': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'other_services': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['app.OtherService']", 'symmetrical': 'False', 'blank': 'True'}),
            'pre_teen_exp': ('django.db.models.fields.SmallIntegerField', [], {'blank': 'True'}),
            'preschool_exp': ('django.db.models.fields.SmallIntegerField', [], {'blank': 'True'}),
            'school_age_exp': ('django.db.models.fields.SmallIntegerField', [], {'blank': 'True'}),
            'sick': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'smoker': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'smokers_ok': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'special_needs_exp': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'teen_exp': ('django.db.models.fields.SmallIntegerField', [], {'blank': 'True'}),
            'three_child_max_rate': ('django.db.models.fields.DecimalField', [], {'max_digits': '5', 'decimal_places': '2', 'blank': 'True'}),
            'three_child_min_rate': ('django.db.models.fields.DecimalField', [], {'max_digits': '5', 'decimal_places': '2', 'blank': 'True'}),
            'toddler_exp': ('django.db.models.fields.SmallIntegerField', [], {'blank': 'True'}),
            'total_exp': ('django.db.models.fields.SmallIntegerField', [], {}),
            'travel_distance': ('django.db.models.fields.PositiveIntegerField', [], {'default': '10'}),
            'two_child_max_rate': ('django.db.models.fields.DecimalField', [], {'max_digits': '5', 'decimal_places': '2', 'blank': 'True'}),
            'two_child_min_rate': ('django.db.models.fields.DecimalField', [], {'max_digits': '5', 'decimal_places': '2', 'blank': 'True'}),
            u'user_ptr': ('django.db.models.fields.related.OneToOneField', [], {'to': u"orm['app.User']", 'unique': 'True', 'primary_key': 'True'}),
            'will_transport': ('django.db.models.fields.BooleanField', [], {'default': 'True'})
        },
        u'app.sitterreview': {
            'Meta': {'unique_together': "(('parent', 'sitter'),)", 'object_name': 'SitterReview'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'parent': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'reviews'", 'to': u"orm['app.Parent']"}),
            'recommended': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'rehire': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'review': ('django.db.models.fields.TextField', [], {'blank': 'True'}),
            'sitter': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'reviews'", 'to': u"orm['app.Sitter']"})
        },
        u'app.specialneed': {
            'Meta': {'object_name': 'SpecialNeed'},
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'need': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        u'app.user': {
            'Meta': {'object_name': 'User'},
            'address1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'address2': ('django.db.models.fields.CharField', [], {'default': "''", 'max_length': '255', 'blank': 'True'}),
            'avatar': ('pyuploadcare.dj.models.ImageField', [], {'blank': 'True'}),
            'cell': ('django.db.models.fields.CharField', [], {'max_length': '12', 'blank': 'True'}),
            'city': ('django.db.models.fields.CharField', [], {'max_length': '50', 'blank': 'True'}),
            'created': ('model_utils.fields.AutoCreatedField', [], {'default': 'datetime.datetime.now'}),
            'date_joined': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '75', 'blank': 'True'}),
            'facebook_id': ('django.db.models.fields.IntegerField', [], {'unique': 'True', 'null': 'True', 'blank': 'True'}),
            'facebook_token': ('django.db.models.fields.CharField', [], {'max_length': '256', 'null': 'True', 'blank': 'True'}),
            'first_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'friends': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'friends_rel_+'", 'blank': 'True', 'to': u"orm['app.User']"}),
            'google_imported': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'invited_by': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['app.User']", 'symmetrical': 'False', 'blank': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_staff': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'languages': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "'users'", 'blank': 'True', 'to': u"orm['app.Language']"}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'last_name': ('django.db.models.fields.CharField', [], {'max_length': '30', 'blank': 'True'}),
            'membership_exp_date': ('django.db.models.fields.DateTimeField', [], {'null': 'True'}),
            'modified': ('model_utils.fields.AutoLastModifiedField', [], {'default': 'datetime.datetime.now'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'sitter_groups': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['app.Group']", 'symmetrical': 'False', 'blank': 'True'}),
            'state': ('django.db.models.fields.CharField', [], {'default': "'AL'", 'max_length': '2', 'blank': 'True'}),
            'status': ('django.db.models.fields.CharField', [], {'default': "'Trial'", 'max_length': '10'}),
            'timezone': ('django.db.models.fields.CharField', [], {'max_length': '255', 'blank': 'True'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'}),
            'username': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30'}),
            'users_in_network': ('django.db.models.fields.related.ManyToManyField', [], {'related_name': "'users_in_network_rel_+'", 'blank': 'True', 'to': u"orm['app.User']"}),
            'zip': ('django.db.models.fields.CharField', [], {'max_length': '9', 'blank': 'True'})
        },
        u'auth.group': {
            'Meta': {'object_name': 'Group'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'auth.permission': {
            'Meta': {'ordering': "(u'content_type__app_label', u'content_type__model', u'codename')", 'unique_together': "((u'content_type', u'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['contenttypes.ContentType']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        }
    }

    complete_apps = ['app']