---

- hosts: all
  roles:
    - common
    - application
    - uwsgi

- hosts: development
  roles:
    - postgres
    - ngrok
    - nodejs
    - redis
    - celeryd
    - celerybeat
    - dev
  vars:
    celery_state: 'started'
    ngrok_tunnels: 'web'
    with_redmon: false
