---

- hosts: all
  become: true
  become_method: 'sudo'
  become_user: 'root'
  roles:
    - common
    - nodejs
    - supervisord
    - nginx
    - uwsgi
    - api

- hosts: development
  roles:
    - postgres
    - redis
    - beatcop
    - celeryd
    - dev
