---

- hosts: all
  roles:
    - common
    - nodejs
    - application
    - uwsgi

- hosts: development
  roles:
    - postgres
    - ngrok
    - redis
    - beatcop
    - celeryd
    - dev
  vars:
    celeryd_state: 'started'
    ngrok_tunnels: 'web'
    with_redmon: false
