---

- name: install uwsgi (via pip)
  pip:
    name=uwsgi
    version=2.0.7

- name: create the uwsgi config directory
  file:
    dest=/etc/uwsgi.d/
    owner=root
    group=root
    mode=755
    state=directory

- name: create the uwsgi upstart script
  template:
    src=uwsgi.conf
    dest=/etc/init/uwsgi.conf
    owner=root
    group=root
    mode=644
  notify:
    - restart uwsgi

- name: enable uwsgi on boot
  service:
    name=uwsgi
    state=stopped
    enabled=true
