---

- name: create the uwsgi config directory
  sudo: true
  file:
    dest=/etc/uwsgi.d/
    owner=root
    group=root
    mode=755
    state=directory

- name: create the uwsgi config
  sudo: True
  template:
    src=sitterfied.ini.j2
    dest=/etc/uwsgi.d/sitterfied.ini
    owner=root
    group=root
    mode=644
  notify:
    - restart uwsgi

- name: create the uwsgi upstart script
  sudo: True
  template:
    src=uwsgi.conf.j2
    dest=/etc/init/uwsgi.conf
    owner=root
    group=root
    mode=644
  notify:
    - restart uwsgi

- name: start and enable the uwsgi service
  sudo: True
  service:
    name=uwsgi
    state=started
    enabled=True
